// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7k4NeTJTh0vCF2hsfNYwzJ-GHpzZ-R0Q',
    appId: '1:1029300321748:web:615e16e00854088611ea41',
    messagingSenderId: '1029300321748',
    projectId: 'chatapp-fe132',
    authDomain: 'chatapp-fe132.firebaseapp.com',
    storageBucket: 'chatapp-fe132.firebasestorage.app',
    measurementId: 'G-M2BT2NETZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Ql6-c40qgoPLLN1MVGLmyHrF-1qaz3Y',
    appId: '1:1029300321748:android:3da1a4239823417a11ea41',
    messagingSenderId: '1029300321748',
    projectId: 'chatapp-fe132',
    storageBucket: 'chatapp-fe132.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9dlTB70edTOn8z4z2CkdjEqxt2O4raL0',
    appId: '1:1029300321748:ios:8cbd8ce54164744411ea41',
    messagingSenderId: '1029300321748',
    projectId: 'chatapp-fe132',
    storageBucket: 'chatapp-fe132.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9dlTB70edTOn8z4z2CkdjEqxt2O4raL0',
    appId: '1:1029300321748:ios:8cbd8ce54164744411ea41',
    messagingSenderId: '1029300321748',
    projectId: 'chatapp-fe132',
    storageBucket: 'chatapp-fe132.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7k4NeTJTh0vCF2hsfNYwzJ-GHpzZ-R0Q',
    appId: '1:1029300321748:web:6f2bee6ad7369f2e11ea41',
    messagingSenderId: '1029300321748',
    projectId: 'chatapp-fe132',
    authDomain: 'chatapp-fe132.firebaseapp.com',
    storageBucket: 'chatapp-fe132.firebasestorage.app',
    measurementId: 'G-K73JZ18QYQ',
  );
}
